### ISSUE TITLE
Tests appear to be broken

### ISSUE THREAD

**Issue by f3mshep** [learn-co-curriculum/js-templates-template-engines-lab#1]
it('builds the proper templates', () => {
        var spy = expect.spyOn(window._, 'template').andCallThrough()
        createPost()
    
        expect(spy).toHaveBeenCalledWith(document.getElementById("page-template").innerHTML)
        expect(spy).toHaveBeenCalledWith(document.getElementById("post-template").innerHTML)
      })

**Comment by dkStephanos** [comment]
yes!!! these tests are terrible. please address this!

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @f3mshep.

This lesson and section are currently under review by our curriculum team. We have referenced your issue and will resolve it in an upcoming version update.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
