### ISSUE TITLE
Tests are awful

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/js-templates-template-engines-lab#2]
The tests don't even seem to make sure you are doing the lab correctly. That and I wasted a ton of time trying to access a form inside a script tag, because the tests told me to put it there, and could only pass the lab when I repeated the same form outside of the tag. This lab needs better instructions, way better tests, and some people who can actually help you with it, appears all the Learn personal just knows Handlebars...

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @dkStephanos.

This lesson and section are currently under review by our curriculum team. We have referenced your issue and will resolve it in an upcoming version update.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
