### ISSUE TITLE
Insufficient Practice, Material, and Time Given to Complete this Lab In order of curriculum

### ISSUE THREAD

**Issue by CatalanoWebDevelopment** [learn-co-curriculum/js-templates-template-engines-lab#3]
I personally do not feel as if the tests in this lab guide the user even remotely enough to finish without looking at the solution. More labs need to come before this breaking up the parts into smaller sections before being hit with creating an entire "simple" blog. This is far too challenging to do after learning brand new information. Please correct this.

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @CatalanoWebDevelopment.

This lesson and section are currently under review by our curriculum team. We have referenced your issue and will resolve it in an upcoming version update.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
