### ISSUE TITLE
mocha-jsdom needs at least version 10.0.0 of jsdom when running the test suite with "learn test".

### ISSUE THREAD

**Issue by Emanao** [learn-co-curriculum/js-templates-template-engines-lab#4]
npm package description is requiring: "jsdom": "^9.4.1" resulting in 9.12.0 being installed what is insufficient to run the tests.

See error below:
/ ♥ learn test
java-script-lodash-templates-lab@0.1.0 /Users/xxx/Desktop/Flatiron/code/js-templates-template-engines-lab-v-000
├── UNMET PEER DEPENDENCY jsdom@9.12.0
└── mocha-jsdom@1.2.0

npm WARN mocha-jsdom@1.2.0 requires a peer of jsdom@>10.0.0 but none was installed.

> java-script-lodash-templates-lab@0.1.0 test /Users/xxx/Desktop/Flatiron/code/js-templates-template-engines-lab-v-000
> mocha -R mocha-multi --reporter-options nyan=-,json=.results.json

 0   -__,------,
 1   -__|  /\_/\
 0   -_~|_( x .x)
     -_ ""  ""

  0 passing (12ms)
  1 failing

  1)  "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:20:19)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)

npm ERR! Test failed.  See above for more details.

**Comment by DiloromA** [comment]
Same problem here.

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @Emanao and @Dillorom .

This lesson and section are currently under review by our curriculum team. We have referenced your issue and will resolve it in an upcoming version update.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
