### ISSUE TITLE
Lab will not show up as completed.

### ISSUE THREAD

**Issue by hong-werdna** [learn-co-curriculum/js-templates-template-engines-lab#5]
Completed lab, and submitted accordingly. Within learn.co module, lesson is not showing up with a green check mark.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @AndrewHongUW.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
