### ISSUE TITLE
npm link as resource is too broad; unclear why it's here when something more helpful could be + some general comments about the section. 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-templates-template-engines-lab#6]
There should be a link to a site that helps, because the lesson wasn't organized enough in its content and detail to make doing this lab straightforward. I haven't been commenting as I go through, because it's time-consuming, but these lessons really do need to be edited and rethought so that enough detail is covered and they match the quality of Ruby and Rails lessons. Also, there's too much of a difference between lessons and labs -- and the TC's aren't as skilled at JS as they are at Ruby/Rails, which means it's hard to get help from AAQ when it's needed. The students all talk about this on slack, and even some TC's have privately slacked me to tell me that everyone feels this way. I've done curriculum writing and I know it's hard and I know it's an iterative process but this section is much more frustrating than it needs to be and it does need to be rewritten to make it easier for students to learn. I know it will be too late for me, but this should definitely be done. For the most part I've stopped making comments each time there's an inconsistency, or basic info is left out, or there's a lesson or codealong that doesn't work in the browser, but there have only been a few lessons that are of the quality of the Ruby/Rails part of the course. Good luck!

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @MiriamPeskowitz.

This lesson and section are currently under review by our curriculum team. We have referenced your issue and will resolve it in an upcoming version update.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
