### ISSUE TITLE
Please Make a Walkthrough for Future Students

### ISSUE THREAD

**Issue by AkaKuro4Ever** [learn-co-curriculum/js-templates-template-engines-lab#7]
This would've been a great walkthrough, but I have to say that this was extremely, overly complex for such a simplistic example. I had to write my own notes and analyze the solution code. 3 learn experts did not know what to do with this. The criteria to pass this is not stuff students would have ever thought of.

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @AkaKuro4Ever.

This lesson and section are currently under review by our curriculum team. We have referenced your issue and will resolve it in an upcoming version update.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
