### ISSUE TITLE
Insufficient information to complete lab. 

### ISSUE THREAD

**Issue by emikojima** [learn-co-curriculum/js-templates-template-engines-lab#8]
I worked on this lab for the whole day today and went 4 rounds on Ask A Question and I am still unable to complete this lab and the TCs were great, but also were unable to tell me what this lab was trying to accomplish. 

It is unclear how all 4 templates fit together from the instructions and it feels like this lab is a HUGE leap from the lessons before it. Is it possible to have:
1. a clear idea of what we are trying to accomplish/ what the end result should look like.
2. another lesson before this lab that tells us how to put a template into a template (if this is something this lab is wanting us to do).

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback, @emikojima.

This lesson and section are currently under review by our curriculum team. We have referenced your issue and will resolve it in an upcoming version update.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
